apiVersion: batch/v1
kind: Job
metadata:
  name: sa-arrow
  namespace: paulhproject
spec:
  backoffLimit: 0
  template:        
    spec:
      containers:
      - name: sa-container
        image: pmh47/slot_attention:latest
        command:
          - "bash"
          - "/workspace/o3d-nerf/slot_attention/train.sh"
        resources:
          requests:
            cpu: "2000m"
            memory: "12Gi"
            nvidia.com/gpu: 1 
          limits:
            cpu: "4000m"
            memory: "16Gi"
            nvidia.com/gpu: 1 
        volumeMounts:
        - mountPath: /workspace
          name: nfs-access
        - mountPath: /dev/shm
          name: dshm
#        env:
#        - name: SOME_ENV_VAR
#          value: "env var value"
      volumes:
      - name: nfs-access
        persistentVolumeClaim:
          claimName: paulhvol1claim
      - name: dshm
        emptyDir:
          medium: Memory
      nodeSelector:
      # gpu2080ti or gputitan or gpu3090
        node-role.ida/gputitan: "true"
      restartPolicy: Never
